# Generated by Django 4.1.6 on 2023-02-19 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manaTransaction', '0002_historytransaction_note_alter_infouser_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='infouser',
            name='pro5_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='historytransaction',
            name='amount_money',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='historytransaction',
            name='type',
            field=models.CharField(choices=[('Rút tiền', 'rut tien'), ('Nạp tiền', 'nap tien')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historytransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userHis', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='balance',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='infouser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
